# This is a basic workflow to help you get started with Actions

name: dev CI workflow

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    test:
        # The type of runner that the job will run on
        strategy:
            matrix:
                python-versions: [3.6, 3.7, 3.8, 3.9]
                os: [ubuntu-20.04, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-versions }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install tox tox-gh-actions poetry

            - name: build documentation
              run: |
                  poetry lock
                  poetry install -E dev
                  poetry run mkdocs build
                  git config --global user.name Docs deploy
                  git config --global user.email docs@dummy.bot.com
                  poetry run mike deploy -p -f --ignore "`poetry version --short`.dev"
                  poetry run mike set-default -p "`poetry version --short`.dev"

            - name: Build wheels and source tarball
              run: |
                  poetry version $(poetry version --short)-dev.$GITHUB_RUN_NUMBER
                  poetry lock
                  poetry build

            - name: publish to Test PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.TEST_PYPI_API_TOKEN}}
                  repository_url: https://test.pypi.org/legacy/
                  skip_existing: true

            - name: test with tox
              run: tox

            - name: list files
              run: ls -l .
